name: Deploy to Serve

on:
  # 在针对 `main` 分支的推送上运行。如果你
  # 使用 `master` 分支作为默认分支，请将其更改为 `master`
  push:
    branches: [release]

  # 允许你从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许同时进行一次部署，跳过正在运行和最新队列之间的运行队列
# 但是，不要取消正在进行的运行，因为我们希望允许这些生产部署完成
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # 构建工作
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 如果未启用 lastUpdated，则不需要
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn # 或 pnpm / yarn
      # - uses: pnpm/action-setup@v3 # 如果使用
      # - uses: oven-sh/setup-bun@v1 # 如果使用 Bun，请取消注释
      - name: Install dependencies
        run: yarn install # 或 pnpm install / yarn install / bun install
      - name: Build
        run: yarn build # 或 pnpm docs:build / yarn docs:build / bun run docs:build
      # - name: Deploy to Server
      #   env:
      #     SERVER_USER: ${{ secrets.SERVER_USER }}
      #     SERVER_IP: ${{ secrets.SERVER_IP }}
      #     SERVER_DIR: ${{ secrets.SERVER_DIR }}
      #     SERVER_USER_PASSWORD: ${{ secrets.SERVER_USER_PASSWORD }}
      #   run: |
      #     sshpass -p $SERVER_USER_PASSWORD sshcompress -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "mkdir -p $SERVER_DIR && rsync -av --delete --exclude=.git /github/home/$GITHUB_REPOSITORY/ $SERVER_USER@$SERVER_IP:$SERVER_DIR"
